# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwin_vid3.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1827, 1059)
        MainWindow.setStatusTip("")
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setStyleSheet("font: 12pt \"微软雅黑\";\n"
"                                font-weight:bold;\n"
"                            ")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_13 = QtWidgets.QLabel(self.frame_3)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_3.addWidget(self.label_13)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.groupBox = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 0, 0, 1, 1)
        self.detWeightsComboBox = QtWidgets.QComboBox(self.groupBox)
        self.detWeightsComboBox.setObjectName("detWeightsComboBox")
        self.gridLayout_5.addWidget(self.detWeightsComboBox, 0, 1, 1, 1)
        self.gridLayout_5.setColumnStretch(0, 1)
        self.gridLayout_5.setColumnStretch(1, 2)
        self.verticalLayout_7.addLayout(self.gridLayout_5)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_10.addWidget(self.label_15)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.picIouSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.picIouSpinBox.setWrapping(True)
        self.picIouSpinBox.setMinimum(0.0)
        self.picIouSpinBox.setMaximum(1.0)
        self.picIouSpinBox.setSingleStep(0.01)
        self.picIouSpinBox.setObjectName("picIouSpinBox")
        self.horizontalLayout_6.addWidget(self.picIouSpinBox)
        self.picIouSlider = QtWidgets.QSlider(self.groupBox)
        self.picIouSlider.setMaximum(100)
        self.picIouSlider.setSingleStep(1)
        self.picIouSlider.setOrientation(QtCore.Qt.Horizontal)
        self.picIouSlider.setObjectName("picIouSlider")
        self.horizontalLayout_6.addWidget(self.picIouSlider)
        self.verticalLayout_10.addLayout(self.horizontalLayout_6)
        self.verticalLayout_7.addLayout(self.verticalLayout_10)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_12.addWidget(self.label_16)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.picConfSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.picConfSpinBox.setWrapping(True)
        self.picConfSpinBox.setMaximum(1.0)
        self.picConfSpinBox.setSingleStep(0.01)
        self.picConfSpinBox.setObjectName("picConfSpinBox")
        self.horizontalLayout_8.addWidget(self.picConfSpinBox)
        self.picConfSlider = QtWidgets.QSlider(self.groupBox)
        self.picConfSlider.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.picConfSlider.setMaximum(100)
        self.picConfSlider.setOrientation(QtCore.Qt.Horizontal)
        self.picConfSlider.setObjectName("picConfSlider")
        self.horizontalLayout_8.addWidget(self.picConfSlider)
        self.verticalLayout_12.addLayout(self.horizontalLayout_8)
        self.verticalLayout_7.addLayout(self.verticalLayout_12)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.cpuRaidoButton = QtWidgets.QRadioButton(self.groupBox)
        self.cpuRaidoButton.setChecked(True)
        self.cpuRaidoButton.setAutoExclusive(True)
        self.cpuRaidoButton.setObjectName("cpuRaidoButton")
        self.horizontalLayout_7.addWidget(self.cpuRaidoButton)
        self.gpuRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.gpuRadioButton.setObjectName("gpuRadioButton")
        self.horizontalLayout_7.addWidget(self.gpuRadioButton)
        self.pic_model_load_button = QtWidgets.QPushButton(self.groupBox)
        self.pic_model_load_button.setObjectName("pic_model_load_button")
        self.horizontalLayout_7.addWidget(self.pic_model_load_button)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.verticalLayout_7.setStretch(0, 1)
        self.verticalLayout_7.setStretch(1, 1)
        self.verticalLayout_7.setStretch(2, 1)
        self.verticalLayout_6.addWidget(self.groupBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_19 = QtWidgets.QLabel(self.groupBox_5)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_10.addWidget(self.label_19)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_10.addWidget(self.lineEdit_2)
        self.label_20 = QtWidgets.QLabel(self.groupBox_5)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_10.addWidget(self.label_20)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_10.addWidget(self.lineEdit_3)
        self.verticalLayout_15.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self.detectLineWidthSpinBox = QtWidgets.QSpinBox(self.groupBox_5)
        self.detectLineWidthSpinBox.setObjectName("detectLineWidthSpinBox")
        self.horizontalLayout_11.addWidget(self.detectLineWidthSpinBox)
        self.horizontalLayout_11.setStretch(0, 3)
        self.horizontalLayout_11.setStretch(1, 3)
        self.verticalLayout_15.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.showLabelCheckBox = QtWidgets.QCheckBox(self.groupBox_5)
        self.showLabelCheckBox.setChecked(True)
        self.showLabelCheckBox.setObjectName("showLabelCheckBox")
        self.horizontalLayout_12.addWidget(self.showLabelCheckBox)
        self.showConfCheckBox = QtWidgets.QCheckBox(self.groupBox_5)
        self.showConfCheckBox.setChecked(True)
        self.showConfCheckBox.setObjectName("showConfCheckBox")
        self.horizontalLayout_12.addWidget(self.showConfCheckBox)
        self.showDiaCheckBox = QtWidgets.QCheckBox(self.groupBox_5)
        self.showDiaCheckBox.setChecked(True)
        self.showDiaCheckBox.setObjectName("showDiaCheckBox")
        self.horizontalLayout_12.addWidget(self.showDiaCheckBox)
        self.verticalLayout_15.addLayout(self.horizontalLayout_12)
        self.getPicSizeButton = QtWidgets.QPushButton(self.groupBox_5)
        self.getPicSizeButton.setObjectName("getPicSizeButton")
        self.verticalLayout_15.addWidget(self.getPicSizeButton)
        self.verticalLayout_15.setStretch(0, 1)
        self.verticalLayout_15.setStretch(1, 2)
        self.verticalLayout_15.setStretch(2, 2)
        self.verticalLayout_6.addWidget(self.groupBox_5)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        spacerItem3 = QtWidgets.QSpacerItem(28, 38, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_4.addWidget(self.lineEdit)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.freeRadioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.freeRadioButton.setChecked(True)
        self.freeRadioButton.setObjectName("freeRadioButton")
        self.horizontalLayout_9.addWidget(self.freeRadioButton)
        self.verticalRadioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.verticalRadioButton.setObjectName("verticalRadioButton")
        self.horizontalLayout_9.addWidget(self.verticalRadioButton)
        self.horizontalRadioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.horizontalRadioButton.setObjectName("horizontalRadioButton")
        self.horizontalLayout_9.addWidget(self.horizontalRadioButton)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.set_cali_button = QtWidgets.QPushButton(self.groupBox_2)
        self.set_cali_button.setObjectName("set_cali_button")
        self.horizontalLayout_5.addWidget(self.set_cali_button)
        self.con_cali_button = QtWidgets.QPushButton(self.groupBox_2)
        self.con_cali_button.setObjectName("con_cali_button")
        self.horizontalLayout_5.addWidget(self.con_cali_button)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.addTextEdit = QtWidgets.QTextEdit(self.groupBox_3)
        self.addTextEdit.setObjectName("addTextEdit")
        self.verticalLayout_9.addWidget(self.addTextEdit)
        self.verticalLayout_6.addWidget(self.groupBox_3)
        self.verticalLayout_6.setStretch(0, 1)
        self.verticalLayout_6.setStretch(1, 3)
        self.verticalLayout_6.setStretch(3, 3)
        self.verticalLayout_6.setStretch(5, 2)
        self.verticalLayout_6.setStretch(7, 2)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.imgVerticalLayout = QtWidgets.QVBoxLayout()
        self.imgVerticalLayout.setObjectName("imgVerticalLayout")
        self.verticalLayout_2.addLayout(self.imgVerticalLayout)
        self.verticalLayout.addWidget(self.frame)
        self.picProgressBar = QtWidgets.QProgressBar(self.tab)
        self.picProgressBar.setProperty("value", 0)
        self.picProgressBar.setTextVisible(False)
        self.picProgressBar.setObjectName("picProgressBar")
        self.verticalLayout.addWidget(self.picProgressBar)
        self.verticalLayout.setStretch(0, 10)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 4, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame_2)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.label_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame_2)
        self.label_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_18.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.gridLayout_2.addLayout(self.verticalLayout_19, 1, 0, 1, 2)
        self.gridLayout_2.setRowStretch(0, 2)
        self.gridLayout_2.setRowStretch(1, 20)
        self.gridLayout_2.setRowStretch(2, 1)
        self.gridLayout_2.setRowStretch(3, 1)
        self.gridLayout_2.setRowStretch(4, 1)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.logTextEdit = QtWidgets.QTextEdit(self.groupBox_4)
        self.logTextEdit.setObjectName("logTextEdit")
        self.verticalLayout_14.addWidget(self.logTextEdit)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.clearButton = QtWidgets.QPushButton(self.tab)
        self.clearButton.setObjectName("clearButton")
        self.gridLayout.addWidget(self.clearButton, 1, 3, 1, 1)
        self.saveButton = QtWidgets.QPushButton(self.tab)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout.addWidget(self.saveButton, 0, 3, 1, 1)
        self.withdrawButton = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.withdrawButton.sizePolicy().hasHeightForWidth())
        self.withdrawButton.setSizePolicy(sizePolicy)
        self.withdrawButton.setObjectName("withdrawButton")
        self.gridLayout.addWidget(self.withdrawButton, 0, 2, 2, 1)
        self.up_img_button = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.up_img_button.sizePolicy().hasHeightForWidth())
        self.up_img_button.setSizePolicy(sizePolicy)
        self.up_img_button.setObjectName("up_img_button")
        self.gridLayout.addWidget(self.up_img_button, 0, 0, 2, 1)
        self.det_img_button = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.det_img_button.sizePolicy().hasHeightForWidth())
        self.det_img_button.setSizePolicy(sizePolicy)
        self.det_img_button.setObjectName("det_img_button")
        self.gridLayout.addWidget(self.det_img_button, 0, 1, 2, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_3.setStretch(0, 10)
        self.verticalLayout_3.setStretch(1, 2)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout.setStretch(0, 4)
        self.horizontalLayout.setStretch(1, 2)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.vidVerticalLayout = QtWidgets.QVBoxLayout()
        self.vidVerticalLayout.setObjectName("vidVerticalLayout")
        self.horizontalLayout_16.addLayout(self.vidVerticalLayout)
        self.verticalLayout_11.addLayout(self.horizontalLayout_16)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.playVidPushButton = QtWidgets.QPushButton(self.tab_2)
        self.playVidPushButton.setObjectName("playVidPushButton")
        self.horizontalLayout_15.addWidget(self.playVidPushButton)
        self.vidProgressHorizontalSlider = QtWidgets.QSlider(self.tab_2)
        self.vidProgressHorizontalSlider.setMinimum(1)
        self.vidProgressHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.vidProgressHorizontalSlider.setObjectName("vidProgressHorizontalSlider")
        self.horizontalLayout_15.addWidget(self.vidProgressHorizontalSlider)
        self.label_26 = QtWidgets.QLabel(self.tab_2)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_15.addWidget(self.label_26)
        self.saveFramePushButton = QtWidgets.QPushButton(self.tab_2)
        self.saveFramePushButton.setObjectName("saveFramePushButton")
        self.horizontalLayout_15.addWidget(self.saveFramePushButton)
        self.verticalLayout_21.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_6.addWidget(self.checkBox_3, 0, 0, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout_6.addWidget(self.checkBox_5, 1, 0, 1, 1)
        self.realTimedetBtn = QtWidgets.QPushButton(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.realTimedetBtn.sizePolicy().hasHeightForWidth())
        self.realTimedetBtn.setSizePolicy(sizePolicy)
        self.realTimedetBtn.setObjectName("realTimedetBtn")
        self.gridLayout_6.addWidget(self.realTimedetBtn, 0, 1, 1, 1)
        self.rtDetStatelabel = QtWidgets.QLabel(self.groupBox_8)
        self.rtDetStatelabel.setObjectName("rtDetStatelabel")
        self.gridLayout_6.addWidget(self.rtDetStatelabel, 1, 1, 1, 1)
        self.horizontalLayout_13.addLayout(self.gridLayout_6)
        self.horizontalLayout_18.addWidget(self.groupBox_8)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_11 = QtWidgets.QLabel(self.groupBox_6)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_13.addWidget(self.label_11)
        self.label_21 = QtWidgets.QLabel(self.groupBox_6)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_13.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.groupBox_6)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_13.addWidget(self.label_22)
        self.horizontalLayout_14.addLayout(self.verticalLayout_13)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.trackDistSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.trackDistSpinBox.setObjectName("trackDistSpinBox")
        self.verticalLayout_16.addWidget(self.trackDistSpinBox)
        self.trackIouSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.trackIouSpinBox.setObjectName("trackIouSpinBox")
        self.verticalLayout_16.addWidget(self.trackIouSpinBox)
        self.trackAgeSpinBox = QtWidgets.QSpinBox(self.groupBox_6)
        self.trackAgeSpinBox.setObjectName("trackAgeSpinBox")
        self.verticalLayout_16.addWidget(self.trackAgeSpinBox)
        self.horizontalLayout_14.addLayout(self.verticalLayout_16)
        self.horizontalLayout_14.setStretch(0, 2)
        self.horizontalLayout_14.setStretch(1, 3)
        self.horizontalLayout_18.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_23 = QtWidgets.QLabel(self.groupBox_7)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 0, 0, 1, 1)
        self.originalFrameSpinBox = QtWidgets.QSpinBox(self.groupBox_7)
        self.originalFrameSpinBox.setMinimum(1)
        self.originalFrameSpinBox.setMaximum(500)
        self.originalFrameSpinBox.setObjectName("originalFrameSpinBox")
        self.gridLayout_3.addWidget(self.originalFrameSpinBox, 0, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_7)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 1, 0, 1, 1)
        self.outputFrameSpinBox = QtWidgets.QSpinBox(self.groupBox_7)
        self.outputFrameSpinBox.setMinimum(1)
        self.outputFrameSpinBox.setMaximum(500)
        self.outputFrameSpinBox.setObjectName("outputFrameSpinBox")
        self.gridLayout_3.addWidget(self.outputFrameSpinBox, 1, 1, 1, 1)
        self.setPlotScopePushButton = QtWidgets.QPushButton(self.groupBox_7)
        self.setPlotScopePushButton.setObjectName("setPlotScopePushButton")
        self.gridLayout_3.addWidget(self.setPlotScopePushButton, 2, 0, 1, 1)
        self.conScopePushButton = QtWidgets.QPushButton(self.groupBox_7)
        self.conScopePushButton.setObjectName("conScopePushButton")
        self.gridLayout_3.addWidget(self.conScopePushButton, 2, 1, 1, 1)
        self.horizontalLayout_18.addWidget(self.groupBox_7)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.loadVidPushButton = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadVidPushButton.sizePolicy().hasHeightForWidth())
        self.loadVidPushButton.setSizePolicy(sizePolicy)
        self.loadVidPushButton.setAutoExclusive(False)
        self.loadVidPushButton.setFlat(False)
        self.loadVidPushButton.setObjectName("loadVidPushButton")
        self.gridLayout_4.addWidget(self.loadVidPushButton, 0, 0, 1, 1)
        self.detVidPushButton = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.detVidPushButton.sizePolicy().hasHeightForWidth())
        self.detVidPushButton.setSizePolicy(sizePolicy)
        self.detVidPushButton.setObjectName("detVidPushButton")
        self.gridLayout_4.addWidget(self.detVidPushButton, 1, 0, 1, 1)
        self.stopVidDetButton = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopVidDetButton.sizePolicy().hasHeightForWidth())
        self.stopVidDetButton.setSizePolicy(sizePolicy)
        self.stopVidDetButton.setObjectName("stopVidDetButton")
        self.gridLayout_4.addWidget(self.stopVidDetButton, 2, 0, 1, 1)
        self.horizontalLayout_18.addLayout(self.gridLayout_4)
        self.horizontalLayout_18.setStretch(0, 2)
        self.horizontalLayout_18.setStretch(1, 2)
        self.horizontalLayout_18.setStretch(2, 2)
        self.horizontalLayout_18.setStretch(3, 1)
        self.verticalLayout_21.addLayout(self.horizontalLayout_18)
        self.verticalLayout_11.addLayout(self.verticalLayout_21)
        self.verticalLayout_11.setStretch(0, 5)
        self.verticalLayout_11.setStretch(1, 1)
        self.horizontalLayout_19.addLayout(self.verticalLayout_11)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.vidDetLogEdit = QtWidgets.QGroupBox(self.tab_2)
        self.vidDetLogEdit.setObjectName("vidDetLogEdit")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.vidDetLogEdit)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.vidLogTextEdit = QtWidgets.QTextEdit(self.vidDetLogEdit)
        self.vidLogTextEdit.setObjectName("vidLogTextEdit")
        self.verticalLayout_17.addWidget(self.vidLogTextEdit)
        self.verticalLayout_20.addWidget(self.vidDetLogEdit)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.saveTrackResulesCheckBox = QtWidgets.QCheckBox(self.tab_2)
        self.saveTrackResulesCheckBox.setObjectName("saveTrackResulesCheckBox")
        self.horizontalLayout_17.addWidget(self.saveTrackResulesCheckBox)
        self.vidProgressBar = QtWidgets.QProgressBar(self.tab_2)
        self.vidProgressBar.setProperty("value", 24)
        self.vidProgressBar.setTextVisible(False)
        self.vidProgressBar.setObjectName("vidProgressBar")
        self.horizontalLayout_17.addWidget(self.vidProgressBar)
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_17.addWidget(self.pushButton)
        self.verticalLayout_20.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_19.addLayout(self.verticalLayout_20)
        self.horizontalLayout_19.setStretch(0, 3)
        self.horizontalLayout_19.setStretch(1, 2)
        self.verticalLayout_18.addLayout(self.horizontalLayout_19)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1827, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setStatusTip("")
        self.statusbar.setAutoFillBackground(False)
        self.statusbar.setStyleSheet("")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionInstructions = QtWidgets.QAction(MainWindow)
        self.actionInstructions.setObjectName("actionInstructions")
        self.menu.addAction(self.actionInstructions)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "液滴识别分析系统"))
        self.label_13.setText(_translate("MainWindow", "设置setting"))
        self.groupBox.setTitle(_translate("MainWindow", "模型"))
        self.label_14.setText(_translate("MainWindow", "模型选择"))
        self.label_15.setText(_translate("MainWindow", "IoU"))
        self.label_16.setText(_translate("MainWindow", "置信度"))
        self.cpuRaidoButton.setText(_translate("MainWindow", "CPU"))
        self.gpuRadioButton.setText(_translate("MainWindow", "GPU(cuda:0)"))
        self.pic_model_load_button.setText(_translate("MainWindow", "加载模型"))
        self.groupBox_5.setTitle(_translate("MainWindow", "图像"))
        self.label_19.setText(_translate("MainWindow", "设置输入图像尺寸"))
        self.label_20.setText(_translate("MainWindow", "*"))
        self.label_12.setText(_translate("MainWindow", "识别框线宽(pixels)"))
        self.showLabelCheckBox.setText(_translate("MainWindow", "显示标签"))
        self.showConfCheckBox.setText(_translate("MainWindow", "显示置信度"))
        self.showDiaCheckBox.setText(_translate("MainWindow", "显示直径"))
        self.getPicSizeButton.setText(_translate("MainWindow", "自动获取输入图像尺寸"))
        self.groupBox_2.setTitle(_translate("MainWindow", "标尺"))
        self.label_2.setText(_translate("MainWindow", "设置标尺长度(mm)"))
        self.freeRadioButton.setText(_translate("MainWindow", "自由"))
        self.verticalRadioButton.setText(_translate("MainWindow", "垂直"))
        self.horizontalRadioButton.setText(_translate("MainWindow", "水平"))
        self.set_cali_button.setText(_translate("MainWindow", "绘制"))
        self.con_cali_button.setText(_translate("MainWindow", "应用"))
        self.groupBox_3.setTitle(_translate("MainWindow", "附加信息"))
        self.label_4.setText(_translate("MainWindow", "累计液滴数量："))
        self.label_7.setText(_translate("MainWindow", "-"))
        self.label_17.setText(_translate("MainWindow", "当前检出数量："))
        self.label_3.setText(_translate("MainWindow", "累计液滴尺寸分布"))
        self.label_6.setText(_translate("MainWindow", "-"))
        self.label_18.setText(_translate("MainWindow", "-"))
        self.label_5.setText(_translate("MainWindow", "液滴平均直径(mm)："))
        self.groupBox_4.setTitle(_translate("MainWindow", "日志"))
        self.clearButton.setText(_translate("MainWindow", "清空"))
        self.saveButton.setText(_translate("MainWindow", "导出"))
        self.withdrawButton.setText(_translate("MainWindow", "撤销本次结果"))
        self.up_img_button.setText(_translate("MainWindow", "加载图片"))
        self.det_img_button.setText(_translate("MainWindow", "开始检测"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "图像"))
        self.playVidPushButton.setText(_translate("MainWindow", "Start"))
        self.label_26.setText(_translate("MainWindow", "-/-"))
        self.saveFramePushButton.setText(_translate("MainWindow", "保存该帧"))
        self.groupBox_8.setTitle(_translate("MainWindow", "检测设置"))
        self.checkBox_3.setText(_translate("MainWindow", "显示速度"))
        self.checkBox_5.setText(_translate("MainWindow", "显示ID"))
        self.realTimedetBtn.setText(_translate("MainWindow", "实时检测"))
        self.rtDetStatelabel.setText(_translate("MainWindow", "实时检测：关"))
        self.groupBox_6.setTitle(_translate("MainWindow", "OC-SORT"))
        self.label_11.setText(_translate("MainWindow", "MAX DIST"))
        self.label_21.setText(_translate("MainWindow", "MAX IOU"))
        self.label_22.setText(_translate("MainWindow", "MAX AGE"))
        self.groupBox_7.setTitle(_translate("MainWindow", "视频设置"))
        self.label_23.setText(_translate("MainWindow", "原始帧率"))
        self.label_24.setText(_translate("MainWindow", "输出帧率"))
        self.setPlotScopePushButton.setText(_translate("MainWindow", "绘制坐标范围"))
        self.conScopePushButton.setText(_translate("MainWindow", "应用"))
        self.loadVidPushButton.setText(_translate("MainWindow", "加载视频"))
        self.detVidPushButton.setText(_translate("MainWindow", "开始检测"))
        self.stopVidDetButton.setText(_translate("MainWindow", "结束检测"))
        self.vidDetLogEdit.setTitle(_translate("MainWindow", "日志"))
        self.saveTrackResulesCheckBox.setText(_translate("MainWindow", "保存结果"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "视频"))
        self.menu.setTitle(_translate("MainWindow", "帮助"))
        self.actionInstructions.setText(_translate("MainWindow", "Instructions"))

